@startuml
!include Style.puml
Actor User
participant ":Parser"
User -> ":Parser" : "help"
activate ":Parser"
create ":HelpCommand"
":Parser" -> ":HelpCommand" : HelpCommand()
activate ":HelpCommand"
":Parser" -> ":HelpCommand" : execute()
deactivate ":Parser"
":HelpCommand" -> "<<static>>\n:ClassPackageReader" : getCommandsAndPrintSyntax()
"<<static>>\n:ClassPackageReader" -> ":Command" : getSyntax()
":Command" --> "<<static>>\n:ClassPackageReader" : syntax
"<<static>>\n:ClassPackageReader" --> User : Prints help messages
destroy ":HelpCommand"

@enduml