@startuml
participant Actor
Actor -> HelpCommand : execute
activate HelpCommand
HelpCommand -> ClassPackageReader : getCommandsAndPrintSyntax
activate ClassPackageReader
ClassPackageReader -> ClassPackageReader : getClasses
activate ClassPackageReader
ClassPackageReader -> ClassPackageReader : λ→
activate ClassPackageReader
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader -> ClassPackageReader : λ→
activate ClassPackageReader
ClassPackageReader -> ClassPackageReader : getClass
activate ClassPackageReader
ClassPackageReader -> Ui : printMessage
activate Ui
Ui --> ClassPackageReader
deactivate Ui
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader -> ClassPackageReader : getClasses
activate ClassPackageReader
ClassPackageReader -> ClassPackageReader : λ→
activate ClassPackageReader
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader -> ClassPackageReader : λ→
activate ClassPackageReader
ClassPackageReader -> ClassPackageReader : getClass
activate ClassPackageReader
ClassPackageReader -> Ui : printMessage
activate Ui
Ui --> ClassPackageReader
deactivate Ui
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader -> ClassPackageReader : getClasses
activate ClassPackageReader
ClassPackageReader -> ClassPackageReader : λ→
activate ClassPackageReader
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader -> ClassPackageReader : λ→
activate ClassPackageReader
ClassPackageReader -> ClassPackageReader : getClass
activate ClassPackageReader
ClassPackageReader -> Ui : printMessage
activate Ui
Ui --> ClassPackageReader
deactivate Ui
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader -> ClassPackageReader : getClasses
activate ClassPackageReader
ClassPackageReader -> ClassPackageReader : λ→
activate ClassPackageReader
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader -> ClassPackageReader : λ→
activate ClassPackageReader
ClassPackageReader -> ClassPackageReader : getClass
activate ClassPackageReader
ClassPackageReader -> Ui : printMessage
activate Ui
Ui --> ClassPackageReader
deactivate Ui
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader -> ClassPackageReader : getClasses
activate ClassPackageReader
ClassPackageReader -> ClassPackageReader : λ→
activate ClassPackageReader
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader -> ClassPackageReader : λ→
activate ClassPackageReader
ClassPackageReader -> ClassPackageReader : getClass
activate ClassPackageReader
ClassPackageReader -> Ui : printMessage
activate Ui
Ui --> ClassPackageReader
deactivate Ui
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader -> ClassPackageReader : mergeSet
activate ClassPackageReader
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader -> ClassPackageReader : filterClassesByCommand
activate ClassPackageReader
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader -> ClassPackageReader : sortCommandByName
activate ClassPackageReader
ClassPackageReader -> Anonymous : compare
activate Anonymous
Anonymous --> ClassPackageReader
deactivate Anonymous
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader -> ClassPackageReader : runSyntaxCommands
activate ClassPackageReader
ClassPackageReader --> ClassPackageReader
deactivate ClassPackageReader
ClassPackageReader --> HelpCommand
deactivate ClassPackageReader
HelpCommand -> Ui : printMessage
activate Ui
Ui --> HelpCommand
deactivate Ui
return
@enduml