
@startuml
!include Style.puml
Actor User
User -> ":Parser" : "food [suffix] [arguments]"
activate ":Parser"
":Parser" -> ":Parser" : Get specific command
activate ":Parser"
":Parser" --> ":Parser" : Suffix after food
deactivate ":Parser"
alt suffix = "add"
    ":Parser" -> ":AddFoodCommand" : ":AddFoodCommand"()
activate ":AddFoodCommand"
":AddFoodCommand" --> ":Parser" : input
":Parser" -> ":Parser" : Parse input
activate ":Parser"
":Parser" --> ":AddFoodCommand" : Food Record
deactivate ":Parser"
":AddFoodCommand" -> ":StorageFood" : Add Food Record
":AddFoodCommand" --> ":Parser" : Finish command
deactivate ":AddFoodCommand"
destroy ":AddFoodCommand"

else suffix = "delete"
":Parser" -> ":DeleteFoodCommand" : ":DeleteFoodCommand"()
activate ":DeleteFoodCommand"
":DeleteFoodCommand" -> ":Parser" : Get Index
":Parser" --> ":DeleteFoodCommand" : Index
":DeleteFoodCommand" -> ":StorageFood" : Delete Food
":DeleteFoodCommand" --> ":Parser" : Finish command
deactivate ":DeleteFoodCommand"
destroy ":DeleteFoodCommand"

else suffix = "clear"
":Parser" -> ":ClearFoodCommand" : ":ClearFoodCommand"()
activate ":ClearFoodCommand"
":ClearFoodCommand" -> ":StorageFood" : Clear list
":ClearFoodCommand" --> ":Parser" : Finish command
deactivate ":ClearFoodCommand"
destroy ":ClearFoodCommand"

else suffix = "list"
":Parser" -> ":ListFoodCommand" : ":ListFoodCommand"()
activate ":ListFoodCommand"
":ListFoodCommand" -> ":StorageFood" : List food records
":ListFoodCommand" --> ":Parser" : Finish Command
deactivate ":ListFoodCommand"
destroy ":ListFoodCommand"
end
alt successful
    return finish message
else incorrect syntax
    ":Parser"-->User : Throw Exception
end
@enduml